import express from "express";
import dotenv from "dotenv";
dotenv.config();
import nodemailer from "nodemailer";
import { db } from "../database.js";

const router = express.Router();

router.post("/", async (req, res) => {
  const { firstName, lastName, phone, email, message } = req.body;

  try {
    // Save to database
    await db.execute(
      "INSERT INTO inquiries (first_name, last_name, phone, email, message) VALUES (?, ?, ?, ?, ?)",
      [firstName, lastName, phone, email, message]
    );

    // Send email
    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: process.env.MAIL_USER,
        pass: process.env.MAIL_PASS,
      },
    });
    console.log("MAIL_USER:", process.env.MAIL_USER);
    console.log("MAIL_PASS:", process.env.MAIL_PASS ? "Loaded" : "Missing");

    transporter.verify((error, success) => {
      if (error) {
        console.error("Transporter verification failed:", error);
      } else {
        console.log("Server is ready to send emails");
      }
    });

    const mailOptions = {
      from: `"Yesha Reality Contact Form" <${email}>`,
      to: process.env.MAIL_USER,
      subject: `📬 New Property Inquiry from ${firstName} ${lastName}`,
      html: `
    <div style="font-family: Arial, sans-serif; color: #333; padding: 20px;">
      <h2 style="color: #005bbb;">New Property Inquiry</h2>
      <p>You’ve received a new inquiry from the Yesha Reality website. Here are the details:</p>
      <table style="width: 100%; border-collapse: collapse; margin-top: 10px;">
        <tr>
          <td style="padding: 8px; font-weight: bold;">Name:</td>
          <td style="padding: 8px;">${firstName} ${lastName}</td>
        </tr>
        <tr>
          <td style="padding: 8px; font-weight: bold;">Phone:</td>
          <td style="padding: 8px;">${phone}</td>
        </tr>
        <tr>
          <td style="padding: 8px; font-weight: bold;">Email:</td>
          <td style="padding: 8px;">${email}</td>
        </tr>
        <tr>
          <td style="padding: 8px; font-weight: bold;">Message:</td>
          <td style="padding: 8px;">${message}</td>
        </tr>
      </table>
      <p style="margin-top: 20px;">Please reach out to the client as soon as possible.</p>
      <hr style="margin-top: 30px;" />
      <p style="font-size: 12px; color: #888;">This message was automatically generated by the Yesha Reality contact form.</p>
    </div>
  `,
    };

    await transporter.sendMail(mailOptions);

    res.status(200).json({ message: "Inquiry sent successfully" });
  } catch (err) {
    console.error("Error handling contact form:", err);
    res.status(500).json({ error: "Internal server error" });
  }
});

export default router;
